### ISSUE TITLE
Reference and Citation Completion

### ISSUE THREAD

**Issue by daskol** [nvarner/typst-lsp#323] opened 2023-10-12 16:58 UTC
It seems that there is no support for completion of reference labels. There is completion in case of neither `@entry1` expression nor `#cite("entry1", "entry2")` function call. It would be great to complete at least a single entry within `@`-syntax but support for completion in context `cite()` function is desired as well.

**Comment by NickAcPT** [comment] 2023-10-12 18:48
I think this is a duplicate of #157, at least for the `@`-syntax

**Comment by Enivex** [comment] 2023-11-26 12:18
This can be closed @nvarner

**Closed** 2023-11-27 21:04 UTC
