### ISSUE TITLE
VSC Extension not properly handling symlinks in path

### ISSUE THREAD

**Issue by PgBiel** [nvarner/typst-lsp#89] opened 2023-04-16 17:35 UTC
- **Component**: 
    - [ ] VSCode Extension
    - [x] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: 0.4.0
- **LSP version**: 0.4.0
- **OS version and name**: OpenSUSE Tumbleweed, snapshot 20230402

- [X] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [X] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
Since the latest release (0.4.0 - this did not occur in 0.3.2), when opening a .typ file in a workspace whose path contains symlinks, the extension seems to automatically resolve the symlinks, and, when you click on errors or similar to check where they are, it opens the file again, but on the actual absolute path instead of the symlinked path. This has become somewhat of an annoyance, as my usual workspace uses symlinks in its path.

### Reproduction Steps

1. Create a folder, e.g. `mkdir /tmp/a`
2. Create a typst file in there with an error, e.g. `echo "soajdfo()asdfo" >> /tmp/a/bad.typ`
3. Create a symlink to the folder, e.g. `ln -s /tmp/a /tmp/b`
4. Open the symlink as a workspace in Code/Codium, e.g. `codium /tmp/b`
5. Open the `bad.typ` file, and edit it slightly (e.g. write "abc" at the end) to ensure it is not opened as a preview (but for editing)
6. Open the errors panel, and click the error (to be taken to it)

**Expected Result:** it just takes you to the error in the currently open file
**Actual Result:** it opens the file again, as if it was external to the current project, but in the absolute path (with symlinks resolved) instead of relative to the current (symlinked) directory

**Comment by PgBiel** [comment] 2023-04-16 17:41
This seems to be related to the source caching feature, as, if I add another file (e.g. `a.typ`) that imports the erroring file (`bad.typ`) in the MRE, I can edit the second `bad.typ` file that the LSP opens and those changes won't be noticed by the LSP when compiling `a.typ` (even if `bad.typ` introduces or fixes an error).

**Comment by nvarner** [comment] 2023-04-16 21:21
I can reproduce this, and I suspect I know what the issue is. Taking a closer look now.

**Comment by nvarner** [comment] 2023-04-16 21:40
I pushed a fix to master. Can you test if it fixes the problem? I'm including a build of master so you don't need to set up a development environment (assuming you're also on x86_64, anyway). You can tell the VSCodium extension to use it via the Server Path in settings.

[typst-lsp.zip](https://github.com/nvarner/typst-lsp/files/11244698/typst-lsp.zip)

**Comment by PgBiel** [comment] 2023-04-16 21:50
> I pushed a fix to master. Can you test if it fixes the problem?

Yep, working fine here (compiling from commit 0462fd77eba4d26dd333659994be0bcaa80145fd). Switching back to the bundled LSP reintroduces the issue, so yeah. Thank you!!

**Comment by nvarner** [comment] 2023-04-16 21:58
Perfect! I'm planning to release again within the next day or two, so you'll be good to switch back to bundled soon.

**Closed by nvarner** 2023-04-16 21:58 UTC
