### ISSUE TITLE
Doesn't create a PDF

### ISSUE THREAD

**Issue by MihaMarkic** [nvarner/typst-lsp#41] opened 2023-03-27 08:30 UTC
Perhaps a dumb question, but I installed the VSCode extension (on Windows 10), created a .typ file, entered some random text, saved it. Nothing happens. No pdf is created, nothing in Output window. VSCode is showing "Typst" for document and extension settings for PDF creation are set "onSave".
Am I missing something obvious? Also, perhaps add a paragraph to readme on what to expect (i.e. if configured properly, a NAME.pdf should appear alongside original text).

**Comment by Bramas** [comment] 2023-03-27 12:31
There is an error if you only open a file (not a folder). If you look at the "output" tab, select Typst Langage server in the dropdown and you may see this error 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:26:29
```
I made a PR to fix this error but github don't want me to create PR (possible outage according to the github status)

**Comment by beeb** [comment] 2023-03-27 12:39
Duplicate of https://github.com/nvarner/typst-lsp/issues/36

**Closed** 2023-03-29 05:57 UTC
