### ISSUE TITLE
Unusable after update

### ISSUE THREAD

**Issue by Enivex** [nvarner/typst-lsp#232] opened 2023-08-11 14:13 UTC
- **Component**: 
    - VSCode Extension
    - LSP (used with other editor)
- **Extension version**: 0.8.1 and 0.9.0
- **LSP version**: 0.8.1 and 0.9.0
- **OS version and name**: Windows 11 23H2

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
Loading any file results in a barrage of error messages, while 0.7.2 works.

### Logs
```
[Error - 4:08:49 PM] src\server\lsp.rs:200 { message = could not open file from LSP client; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/redacted/Documents/GitHub/redacted/redacted.typ; }
[Info  - 4:08:49 PM] src\server\lsp.rs:184 { message = server initialized; }
[Error - 4:08:49 PM] Request textDocument/documentSymbol failed.
  Message: Internal error
  Code: -32603 
[Error - 4:08:49 PM] src\server\lsp.rs:388 { message = error getting document symbols; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/redacted/Documents/GitHub/redacted/redacted.typ; }
[Error - 4:08:49 PM] Request textDocument/documentSymbol failed.
  Message: Internal error
  Code: -32603 
[Error - 4:08:49 PM] src\server\lsp.rs:388 { message = error getting document symbols; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/redacted/Documents/GitHub/redacted/redacted.typ; }
[Error - 4:08:50 PM] Request textDocument/semanticTokens/full failed.
  Message: Internal error
  Code: -32603 
[Error - 4:08:50 PM] src\server\lsp.rs:450 { message = error getting full semantic tokens; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/redacted/Documents/GitHub/redacted/redacted.typ; }
[Error - 4:09:40 PM] Request textDocument/documentSymbol failed.
  Message: Internal error
  Code: -32603 
  ```

**Comment by nvarner** [comment] 2023-08-11 15:20
I think this is a URL encoding issue. Would those URIs be correct for your system if they used `c:` instead of `c%3A`?

**Comment by Enivex** [comment] 2023-08-11 15:24
> I think this is a URL encoding issue. Would those URIs be correct for your system if they used `c:` instead of `c%3A`?

There are also some %20 and %27 for space and ' in the file name, but yes.

**Comment by nvarner** [comment] 2023-08-11 20:33
Can you change the setting `typst-lsp.trace.server` to `"verbose"` and see if there are any more relevant logs? I don't have a Windows machine and am struggling to reproduce the issue, so more information would help.

**Comment by Enivex** [comment] 2023-08-11 20:46
> Can you change the setting `typst-lsp.trace.server` to `"verbose"` and see if there are any more relevant logs? I don't have a Windows machine and am struggling to reproduce the issue, so more information would help.

I would, but it actually works on the machine I have available right now. The same uri format (%3a, %20, %27 present) appears in the logs with verbose on, though. Strangely everything should be the same on these machines, so I have no idea what's going on.

Unfortunately I won't be able to test it on the machine it was failing on until monday.

**Comment by nvarner** [comment] 2023-08-11 21:13
I found `rust-analyzer` bug reports from Windows that had the same format, and some newly written encoding tests passed on Windows CI. My initial guess was probably wrong, and the encoding is actually okay.

Given that it's not happening on your other machine, and that this is the only issue filed for this error, I'm hoping it's uncommon. I'll try to improve logging in the relevant code, and if you're able, send in verbose logs when you have access to the computer with the issue. I'll put this on hold until I can get more information.

**Comment by Stivux** [comment] 2023-08-11 22:06
I have same problem with nvim. I don't know how to set the setting "typst-lsp.trace.server" in nvim config, but there is default nvim's [lsp.log](https://pastebin.com/4QjtmYcG)

**Comment by samuzora** [comment] 2023-08-12 07:33
I'm not entirely sure, but it could be caused by the LSP trying to resolve the root directory. Adding a .git/ at the root fixed the error for me.

**Comment by nvarner** [comment] 2023-08-12 12:24
@samuzora can you explain how you added a .git/ to the root? The format of the root directory looks like the most likely culprit as of now.

**Comment by samuzora** [comment] 2023-08-12 12:49
Currently my directory looks like this:

```
.
├── file.pdf
├── file.typ
├── .git
│   ├── branches
│   ├── config
│   ├── description
│   ├── HEAD
│   ├── hooks
...
└── ref.bib
```

I ran `git init` in the same directory as `file.typ`, but just `mkdir .git` works too.

Actually in neovim's LSP, there's an option for single_file_support which shouldn't rely on the root directory, but regardless of the option the .git folder has to be there for the error not to occur. I guess single_file_support isn't compatible with the new versions of typst-lsp? 

If the option is set to false, then nvim-lspconfig will try to resolve the root directory by referencing the .git folder:

```
function M.find_git_ancestor(startpath)
  return M.search_ancestors(startpath, function(path)
    -- Support git directories and git files (worktrees)
    if M.path.is_dir(M.path.join(path, '.git')) or M.path.is_file(M.path.join(path, '.git')) then
      return path
    end
  end)
end
```

**Comment by nvarner** [comment] 2023-08-12 15:54
Your previous log didn't include it, but are you able to find out what root directory or workspace folders the client sends to `typst-lsp`? Single file support isn't part of the LSP, so, they likely have some kind of hack or otherwise break an assumption I'm making. If I have time, I'll investigate how it works to get it working again.

**Comment by samuzora** [comment] 2023-08-12 16:12
Hmm... according to the docs:

```
Some servers support not passing a root directory as a proxy for single file
mode under which cross-file features may be degraded.

`lspconfig` offers limited support for an implicit single-file mode by:

- first trying to resolve the root directory pattern
- then, if `single_file_support` is enabled for a given language server
  configuration, starting the server without sending `rootDirectory` or
  `workspaceFolders` during initialization.
- attaching subsequent files in the parent directory to the same server
  instance, depending on filetype.
- also supports unnamed buffer if filetype matches the server filetype
  settings.
  ```

It just doesn't send the rootDirectory to the LSP server, but attaches any open files that are under the same parent directory to the running server instance. Since some other LSPs also don't support single_file_support, might it be out of scope for typst-lsp?

**Comment by Enivex** [comment] 2023-08-14 09:30
I can confirm that if I open the directory instead of the single file, then it works. But I've not encountered this problem before with other LSPs.

In fact, I rarely open a directory when I edit a document, so this is quite annoying.

**Comment by SillyFreak** [comment] 2023-08-14 10:37
I think I have a related problem. I work with typst in a VS Code workspace with several (six) root folders. In 0.8.1 and 0.9.1, I was able to get the following error message while investigating why I wasn't shown syntax errors:

```
[Error - 12:24:36 PM] src/lsp_typst_boundary.rs:283 { message = could not convert Typst error to diagnostic; conversion_err = could not find `/other/workspace/root/typst-packages/test.typ` on the local filesystem; typst_err = SourceDiagnostic { severity: Error, span: Span(120311945423942), message: "unknown variable: a", trace: [], hints: [] }; }
```

This was while editing `/some/workspace/root/typst-packages/test.typ`. Fwiw, the file was in the first root, and the error tried to refer to a file in the last one.

In another instance, I got an "lsp crashed multiple times in 5 minutes and will not be restarted" message, but I reopened VS Code after that and can't reproduce it. The message there also referred to the same kind of nonexistent path.

**Comment by Saplyng** [comment] 2023-08-15 16:39
I can also confirm what @SillyFreak said, running updated Garuda Linux using code-oss. When multiple folders are in a workspace typst-lsp only looks through the bottommost folder regardless of where you're trying to save/execute doPdfExport

**Comment by ice1000** [comment] 2023-08-15 17:19
I get

```
[Error - 1:18:24 PM] src\server\lsp.rs:451 { message = error getting full semantic tokens; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/ice10/OneDrive/Desktop/Writeups/plans-for-lamett.typ; }
[Error - 1:18:24 PM] Request textDocument/documentSymbol failed.
  Message: Internal error
  Code: -32603 
[Error - 1:18:24 PM] src\server\lsp.rs:389 { message = error getting document symbols; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/ice10/OneDrive/Desktop/Writeups/plans-for-lamett.typ; }
[Error - 1:18:26 PM] src\server\lsp.rs:246 { message = could not handle source save; err = the provider does not provide the requested URI; uri = file:///c%3A/Users/ice10/OneDrive/Desktop/Writeups/plans-for-lamett.typ; }
```

**Comment by nvarner** [comment] 2023-08-15 19:03
I am able to reproduce the behavior @SillyFreak and @Saplyng have reported. I'll investigate now.

**Comment by y2-Whyto** [comment] 2023-08-17 08:24
I encountered the same issue with 0.9.3 on VSCode and I'm using macOS 13.5. Here is my verbose output.

```
[Trace - 16:21:13] Sending request 'initialize - (0)'.
Params: {
    "processId": 55912,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.81.1"
    },
    "locale": "zh-cn",
    "rootPath": null,
    "rootUri": null,
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": false
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "initializationOptions": {
        "exportPdf": "onSave",
        "rootPath": null,
        "semanticTokens": "enable",
        "serverPath": null,
        "trace": {
            "server": "verbose"
        }
    },
    "trace": "verbose",
    "workspaceFolders": null
}


[Trace - 16:21:13] Received response 'initialize - (0)' in 689ms.
Result: {
    "capabilities": {
        "completionProvider": {
            "triggerCharacters": [
                "#",
                ".",
                "@"
            ]
        },
        "documentSymbolProvider": true,
        "executeCommandProvider": {
            "commands": [
                "typst-lsp.doPdfExport",
                "typst-lsp.doClearCache"
            ]
        },
        "hoverProvider": true,
        "selectionRangeProvider": true,
        "signatureHelpProvider": {
            "triggerCharacters": [
                "(",
                ","
            ]
        },
        "textDocumentSync": {
            "change": 2,
            "openClose": true,
            "save": true
        },
        "workspace": {
            "workspaceFolders": {
                "changeNotifications": true,
                "supported": true
            }
        },
        "workspaceSymbolProvider": true
    }
}


[Trace - 16:21:13] Sending notification 'initialized'.
Params: {}


[Trace - 16:21:13] Received notification 'window/logMessage'.
Params: {
    "message": "src/workspace/package/external/manager.rs:48 { message = got user external package directory; user = LocalProvider { root: \"/Users/whyto/Library/Application Support/typst/packages/\" }; }",
    "type": 3
}


[Info  - 16:21:13] src/workspace/package/external/manager.rs:48 { message = got user external package directory; user = LocalProvider { root: "/Users/whyto/Library/Application Support/typst/packages/" }; }
[Trace - 16:21:13] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/whyto/Desktop/1.typ",
        "languageId": "typst",
        "version": 1,
        "text": "#set page(\n    paper: \"a5\",\n    margin: (x: 2cm, y: 2cm)\n)\n\n#set font(\n    \n)\n\n= Intro\n\n"
    }
}


[Trace - 16:21:13] Received notification 'window/logMessage'.
Params: {
    "message": "src/workspace/package/external/manager.rs:58 { message = got external package cache; cache = LocalProvider { root: \"/Users/whyto/Library/Caches/typst/packages/\" }; }",
    "type": 3
}


[Info  - 16:21:13] src/workspace/package/external/manager.rs:58 { message = got external package cache; cache = LocalProvider { root: "/Users/whyto/Library/Caches/typst/packages/" }; }
[Trace - 16:21:13] Received notification 'window/logMessage'.
Params: {
    "message": "src/workspace/package/manager.rs:42 { message = initialized package manager; current = {}; external = ExternalPackageManager { providers: [LocalProvider { root: \"/Users/whyto/Library/Application Support/typst/packages/\" }, LocalProvider { root: \"/Users/whyto/Library/Caches/typst/packages/\" }], cache: Some(LocalProvider { root: \"/Users/whyto/Library/Caches/typst/packages/\" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"packages.typst.org\")), port: None, path: \"/\", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({\"http\": http://127.0.0.1:7890, \"https\": http://127.0.0.1:7890}), None)], referer: true, default_headers: {\"accept\": \"*/*\"}, timeout: 30s } }) }; }",
    "type": 3
}


[Info  - 16:21:13] src/workspace/package/manager.rs:42 { message = initialized package manager; current = {}; external = ExternalPackageManager { providers: [LocalProvider { root: "/Users/whyto/Library/Application Support/typst/packages/" }, LocalProvider { root: "/Users/whyto/Library/Caches/typst/packages/" }], cache: Some(LocalProvider { root: "/Users/whyto/Library/Caches/typst/packages/" }), repo: Some(RemoteRepoProvider { base_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("packages.typst.org")), port: None, path: "/", query: None, fragment: None }, client: Client { accepts: Accepts, proxies: [Proxy(System({"http": http://127.0.0.1:7890, "https": http://127.0.0.1:7890}), None)], referer: true, default_headers: {"accept": "*/*"}, timeout: 30s } }) }; }
[Trace - 16:21:13] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "semantic_tokens",
            "method": "textDocument/semanticTokens",
            "registerOptions": {
                "full": {
                    "delta": true
                },
                "legend": {
                    "tokenModifiers": [
                        "strong",
                        "emph",
                        "math"
                    ],
                    "tokenTypes": [
                        "comment",
                        "string",
                        "keyword",
                        "operator",
                        "number",
                        "function",
                        "decorator",
                        "bool",
                        "punct",
                        "escape",
                        "link",
                        "raw",
                        "label",
                        "ref",
                        "heading",
                        "marker",
                        "term",
                        "delim",
                        "pol",
                        "error",
                        "text"
                    ]
                }
            }
        }
    ]
}


[Trace - 16:21:13] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
No result returned.


[Trace - 16:21:13] Sending request 'textDocument/documentSymbol - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/whyto/Desktop/1.typ"
    }
}


[Trace - 16:21:13] Received notification 'window/logMessage'.
Params: {
    "message": "src/server/lsp.rs:201 { message = could not open file from LSP client; err = the provider does not provide the requested URI; uri = file:///Users/whyto/Desktop/1.typ; }",
    "type": 1
}


[Error - 16:21:13] src/server/lsp.rs:201 { message = could not open file from LSP client; err = the provider does not provide the requested URI; uri = file:///Users/whyto/Desktop/1.typ; }
[Trace - 16:21:13] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "config",
            "method": "workspace/didChangeConfiguration"
        }
    ]
}


[Trace - 16:21:13] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
No result returned.


[Trace - 16:21:13] Received response 'textDocument/documentSymbol - (1)' in 5ms. Request failed: Internal error (-32603).
[Error - 16:21:13] Request textDocument/documentSymbol failed.
  Message: Internal error
  Code: -32603 
[Trace - 16:21:13] Received notification 'window/logMessage'.
Params: {
    "message": "src/server/lsp.rs:389 { message = error getting document symbols; err = the provider does not provide the requested URI; uri = file:///Users/whyto/Desktop/1.typ; }",
    "type": 1
}


[Error - 16:21:13] src/server/lsp.rs:389 { message = error getting document symbols; err = the provider does not provide the requested URI; uri = file:///Users/whyto/Desktop/1.typ; }
[Trace - 16:21:13] Received request 'client/registerCapability - (2)'.
Params: {
    "registrations": [
        {
            "id": "watch_typst_files",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "**/*"
                    }
                ]
            }
        }
    ]
}


[Trace - 16:21:13] Sending response 'client/registerCapability - (2)'. Processing request took 1ms
No result returned.


[Trace - 16:21:13] Received notification 'window/logMessage'.
Params: {
    "message": "src/server/lsp.rs:185 { message = server initialized; }",
    "type": 3
}


[Info  - 16:21:13] src/server/lsp.rs:185 { message = server initialized; }
[Trace - 16:21:14] Sending request 'textDocument/semanticTokens/full - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/whyto/Desktop/1.typ"
    }
}


[Trace - 16:21:14] Received response 'textDocument/semanticTokens/full - (2)' in 1ms. Request failed: Internal error (-32603).
[Error - 16:21:14] Request textDocument/semanticTokens/full failed.
  Message: Internal error
  Code: -32603 
[Trace - 16:21:14] Received notification 'window/logMessage'.
Params: {
    "message": "src/server/lsp.rs:451 { message = error getting full semantic tokens; err = the provider does not provide the requested URI; uri = file:///Users/whyto/Desktop/1.typ; }",
    "type": 1
}


[Error - 16:21:14] src/server/lsp.rs:451 { message = error getting full semantic tokens; err = the provider does not provide the requested URI; uri = file:///Users/whyto/Desktop/1.typ; }
```

**Comment by y2-Whyto** [comment] 2023-08-17 08:30
By the way, I got no syntex highlighting with 0.9.3 on VSCode. This is what it looks like now:

<img width="455" alt="image" src="https://github.com/nvarner/typst-lsp/assets/42339192/0dd6ca16-2240-4c01-8c5b-71a8692203e0">

I haven't find any solution yet, and I don't know if it's related to the bug in this issue. If not, I could create a new issue.

Maybe @cristobaltapia could kindly tell me whether your syntex highlighting feature is working well.

**Comment by cristobaltapia** [comment] 2023-08-17 08:33
@y2-Whyto I am using neovim and my syntax highlighting is working correctly, so maybe that is an unrelated problem.

**Comment by y2-Whyto** [comment] 2023-08-17 09:00
> @y2-Whyto I am using neovim and my syntax highlighting is working correctly, so maybe that is an unrelated problem.

OK. Thanks for your information.

**Comment by Enivex** [comment] 2023-08-18 10:09
This still does not work for me in 0.9.3 if I open only the file and not the folder.

**Comment by YDX-2147483647** [comment] 2023-08-18 17:13
I have the same issue as Enivex across v0.8 – v0.9.3 on Windows 10. I tried to debug on master (bfed5b) for more information …

`message: "error getting full semantic tokens"` on ~~Fahrenheit~~ line 451 of `src/server/lsp.rs` is mentioned above, and `"could not handle source save"` on line 246 also appears occasionally.

https://github.com/nvarner/typst-lsp/blob/bfed5b3367684a0baed6b52d9771d70c4ce04cc4/src/server/lsp.rs#L246

https://github.com/nvarner/typst-lsp/blob/bfed5b3367684a0baed6b52d9771d70c4ce04cc4/src/server/lsp.rs#L451

`error: "the provider does not provide the requested URI"` is from `PackageManager::full_id`. `self.external.full_id(uri)` gets nothing, and `self.current` is empty therefore `self.current_full_id(uri)` also fails to give a reasonable `full_id`.

https://github.com/nvarner/typst-lsp/blob/bfed5b3367684a0baed6b52d9771d70c4ce04cc4/src/workspace/package/manager.rs#L63-L68

https://github.com/nvarner/typst-lsp/blob/bfed5b3367684a0baed6b52d9771d70c4ce04cc4/src/workspace/package/manager.rs#L70-L81

(Empty `candidates` cannot `max_by_key`)

---

Besides, could someone edit the title of this issue? Maybe it can be more specific?

**Comment by nvarner** [comment] 2023-08-19 17:31
I reread the spec, and it does actually include single file support; I must have misread it the first time around. @YDX-2147483647 I think your PR will resolve this, so I'll try to make a release very soon, which should hopefully resolve this issue.

**Comment by nvarner** [comment] 2023-08-19 17:34
In case there are other underlying problems responsible for reports here, please open a new issue, linking to comments in this thread if needed.

**Closed** 2023-08-19 17:45 UTC
Labels: bug, needs investigation
