### ISSUE TITLE
Bug in highlighting

### ISSUE THREAD

**Issue by Alessandro-Monguzzi** [nvarner/typst-lsp#308] opened 2023-09-24 07:29 UTC
- **Component**: 
    - VSCode Extension
- **Extension version**: v0.10.1 
- **OS version and name**: Windows 11

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

As you can see in the screenshot, the sintax highlight is bugged. Also in other cases i find this bugs but i can't reproduce it.
![immagine](https://github.com/nvarner/typst-lsp/assets/74705926/ef0dac44-29e0-4735-b545-645c7e53ac78)

**Comment by nvarner** [comment] 2023-09-24 18:19
Does this issue always occur in this file, or only sometimes? If this file always causes it, can you upload the file here?

In either case, can you post the logs?

**Comment by Myriad-Dreamin** [comment] 2024-01-04 04:42
Could we close it due to no response? I cannot reproduce it on my PC.

**Comment by astrale-sharp** [comment] 2024-01-04 10:30
I agree, I'll close it.

@Alessandro-Monguzzi you can reopen it if you have more information and the problem still exists

**Closed by astrale-sharp** 2024-01-04 10:30 UTC
Labels: bug, question, language server
